/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TldrawRouteImport } from './routes/tldraw'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExicalidrawRouteImport } from './routes/exicalidraw'
import { Route as IndexRouteImport } from './routes/index'

const TldrawRoute = TldrawRouteImport.update({
  id: '/tldraw',
  path: '/tldraw',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExicalidrawRoute = ExicalidrawRouteImport.update({
  id: '/exicalidraw',
  path: '/exicalidraw',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exicalidraw': typeof ExicalidrawRoute
  '/history': typeof HistoryRoute
  '/tldraw': typeof TldrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exicalidraw': typeof ExicalidrawRoute
  '/history': typeof HistoryRoute
  '/tldraw': typeof TldrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exicalidraw': typeof ExicalidrawRoute
  '/history': typeof HistoryRoute
  '/tldraw': typeof TldrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exicalidraw' | '/history' | '/tldraw'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exicalidraw' | '/history' | '/tldraw'
  id: '__root__' | '/' | '/exicalidraw' | '/history' | '/tldraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExicalidrawRoute: typeof ExicalidrawRoute
  HistoryRoute: typeof HistoryRoute
  TldrawRoute: typeof TldrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tldraw': {
      id: '/tldraw'
      path: '/tldraw'
      fullPath: '/tldraw'
      preLoaderRoute: typeof TldrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exicalidraw': {
      id: '/exicalidraw'
      path: '/exicalidraw'
      fullPath: '/exicalidraw'
      preLoaderRoute: typeof ExicalidrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExicalidrawRoute: ExicalidrawRoute,
  HistoryRoute: HistoryRoute,
  TldrawRoute: TldrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
